Upgrade to python 3 and CKAN 2.9
alphagov/ckanext-spatial pull request #28
Opened 2021-02-24 11:14 UTC by kentsanggds

## What

Adds commits from the DGU spatial fork into the smellman fork and fixes various python 2 and 3 issues and problems around harvesting which were uncovered by the harvest tests which are added back in.

## How to review 

In order to review this, it's probably best to focus on the commit following sha b0b8139 (Remove older OWSLib dependency), as the previous commits are added in from our alphagov fork and have been updated for python 3.  After sha b0b8139 these commits were added in to upgrade the harvest test file, fix git action tests and fix csw to work with CKAN 2.9.

Its probably not necessary to run the tests on your own stack as you can see the tests passing on git action tests, I will be doing further end to end testing of the branch using visual regression tests and API functional tests.

Although this branch should be compatible with python 2, I will be focusing on testing it on python 3 and CKAN 2.9, so the merge will be into main-2.9 (forked from smellman/dev-py3) rather than the master branch.

## Reference 

https://trello.com/c/hL3cMBZh/2313-check-out-other-forked-ckanext-spatial-python3-upgrade-pr

2021-02-24 13:17 UTC, thomasleese reviewed
Generally this seems fine, I was mostly focussed on the Python rather than the specifics of how CKAN works because I'm not super familiar with that. I've left a few comments that I think might be worth addressing before approving.

2021-02-24 13:17 UTC, thomasleese commented on ckanext/spatial/harvesters/gemini.py
> +            self.force_import = getattr(harvest_object, 'force_import', False)
I think we can probably merge this change with the commit right before it.

2021-02-24 13:17 UTC, thomasleese commented on ckanext/spatial/tests/functional/test_widgets.py
> +    @pytest.mark.usefixtures('with_plugins', 'clean_db', 'clean_index', 'harvest_setup', 'spatial_setup')
I might be good to explain why we no longer need `clean_postgis` in the commit message.

2021-02-24 18:35 UTC, kentsanggds commented on ckanext/spatial/tests/functional/test_widgets.py
> +    @pytest.mark.usefixtures('with_plugins', 'clean_db', 'clean_index', 'harvest_setup', 'spatial_setup')
OK, will do that

2021-02-24 18:46 UTC, kentsanggds commented on ckanext/spatial/harvesters/gemini.py
> +            self.force_import = getattr(harvest_object, 'force_import', False)
I think I'm going to leave commits as they are as they were previously approved unless its a style or python 2/3 thing

2021-02-24 19:04 UTC, kentsanggds commented on ckanext/spatial/tests/unit/harvesters/test_gemini.py
> +        '..',
I'll see if I can extract it out for readability

2021-02-25 12:39 UTC, 0atman requested changes
phew! What a long PR. Here's my comments, most are suggestions, but you have tests that don't work with invalid `assert` statements. These might be silently failing.

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +from ckanext.spatial.tests.xml_file_server import serve
sort with `isort`

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        # Create a job
does this comment add value?

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        return list(map(lambda x: {u'name': x['name']}, tags))
```suggestion
        return [{u'name': tag['name']} for tag in tags]
```
seems clearer in this case

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        return values[0] if len(values) == 1 else None
```suggestion
        next(iter(values), None)
```
This shorter, I guess? you decide which is better.

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        assert first_obj.current == True
```suggestion
        assert first_obj.current
```

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        assert second_obj.current == False, first_obj.current == True
```suggestion
        assert second_obj.current == False
        assert first_obj.current == True
```
This does not do what you think it does. These two asserts need to be separate, the part after the comma is the error raised if the assertion fails, usually a string describing the error.

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        assert second_obj.current == False, first_obj.current == True
same for all of these asserts, actually

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        assert third_obj.current == True, second_obj.current == False
Assertations do not work like this (see previous comment)

```
>>> assert False, True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: True
```

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        if org is None:
```suggestion
        if not org:
```

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        assert {'name': TAG_LONG_VALID_LONG} in tags
Please make sure these tests are running, they're not valid python.

```python
TypeError: unhashable type: 'dict'
```

I think you want 
```python
assert tags['name'] not TAG_CHARS_VALID
```

etc?

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +        assert (name, set(arr)) == ('Ordnance Survey', set(['Maps Ltd (distributor)', 'Ordnance Survey (publisher)']))
This seems unnecessarily complicated. It's no extra characters to assert the name and the `set(arr)` separately, right?

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_harvest.py
> +                errors += '; ' + validation_errors
```suggestion
                errors += f"; {validation_errors}"
```

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_validation.py
> +        _, errors = validator.is_valid(xml)
```suggestion
        _is_valid, errors = validator.is_valid(xml)
```

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/test_validation.py
> +            'gemini2.1/validation/04_Dataset_Valid.xml'
driveby suggestion: the community seems to be standardising on double-quotes, see `black`.

2021-02-25 12:39 UTC, 0atman commented on ckanext/spatial/tests/xml_file_server.py
> +        self.wfile.write(content.encode('utf-8') if sys.version_info < (3, 0) else bytes(content, "utf-8"))
consider re-writing this long ternary operator as `if/else`

2021-03-01 11:17 UTC, kentsanggds commented on bin/ckan_pycsw.py
> +        log.info("Please upgrade to CKAN 2.9 and python 3")
OK, will update

2021-03-01 11:17 UTC, kentsanggds commented on bin/ckan_pycsw.py
> +    if sys.version_info < (3, 0):
OK, will split up, to make it easier to review

2021-03-01 11:23 UTC, kentsanggds commented on ckanext/spatial/tests/test_harvest.py
> +from ckanext.spatial.tests.xml_file_server import serve
sorted manually

2021-03-01 11:24 UTC, kentsanggds commented on ckanext/spatial/tests/test_harvest.py
> +        # Create a job
I'll remove it

2021-03-01 11:46 UTC, kentsanggds commented on ckanext/spatial/tests/test_harvest.py
> +        assert (name, set(arr)) == ('Ordnance Survey', set(['Maps Ltd (distributor)', 'Ordnance Survey (publisher)']))
OK, have simplified it

2021-03-01 11:47 UTC, kentsanggds commented on ckanext/spatial/tests/test_harvest.py
> +                errors += '; ' + validation_errors
I might just leave this as the main extension is meant to be compatible with python 2 and 3

2021-03-01 11:49 UTC, kentsanggds commented on ckanext/spatial/tests/test_validation.py
> +        _, errors = validator.is_valid(xml)
Not sure if its necessary to change this as _is_valid is not being used?

2021-03-01 11:50 UTC, kentsanggds commented on ckanext/spatial/tests/test_validation.py
> +            'gemini2.1/validation/04_Dataset_Valid.xml'
I'm going to leave this for now as the aim will eventually be to merge it upstream so don't want to introduce too many changes which will make it difficult for the CKAN core team to review

2021-03-01 11:58 UTC, kentsanggds commented on ckanext/spatial/tests/xml_file_server.py
> +        self.wfile.write(content.encode('utf-8') if sys.version_info < (3, 0) else bytes(content, "utf-8"))
ok, will rewrite it

2021-03-01 12:04 UTC, kentsanggds commented on ckanext/spatial/cli.py
>      ]
I think CKAN uses it to determine what commands are available on the CLI

2021-03-01 12:17 UTC, 0atman commented on ckanext/spatial/tests/test_validation.py
> +        _, errors = validator.is_valid(xml)
yes, it's a moot point. However, I think `_is_valid` is better than `_` and `is_valid` as it telegraphs that 1. this variable is intentionally not use and 2 that it's a boolean validity marker, if it is used.

2021-03-01 12:18 UTC, 0atman commented on ckanext/spatial/tests/test_validation.py
> +            'gemini2.1/validation/04_Dataset_Valid.xml'
were the `"` added by the CKAN team or us?

2021-03-01 12:42 UTC, kentsanggds commented on ckanext/spatial/tests/test_validation.py
> +        _, errors = validator.is_valid(xml)
ok, I can change it to improve readability

2021-03-01 12:45 UTC, kentsanggds commented on ckanext/spatial/tests/test_validation.py
> +            'gemini2.1/validation/04_Dataset_Valid.xml'
I think they were added by CKAN contributors, similar things are also in other extensions as well as the core CKAN code

2021-03-02 11:43 UTC, 0atman commented on ckanext/spatial/tests/test_validation.py
> +            'gemini2.1/validation/04_Dataset_Valid.xml'
cool, sounds fine then!

2021-03-02 11:51 UTC, 0atman approved these changes
Nice work! :+1:

2021-03-02 11:54 UTC, merged