Update smellman fork with DGU commits
alphagov/ckanext-spatial pull request #29
Opened 2021-02-24 11:30 UTC by kentsanggds

## What

This PR will update the smellman fork that upgrades the spatial extension to python 3 with DGU commits also upgraded. 

Tests are passing on the dev stack, unfortunately the git action tests are not passing but have been introduced in another branch - https://github.com/alphagov/ckanext-spatial/tree/ckan-2.9, which contains all these commits plus additional commits to add harvest tests, fix git action tests and fix CSW.

## How to review

Ideally you should spin up your own docker ckan dev stack to run the tests manually, otherwise it's probably good to just look over the commits to see if there are any issues in the upgrade code. 

## Reference

https://trello.com/c/hL3cMBZh/2313-check-out-other-forked-ckanext-spatial-python3-upgrade-pr

2021-02-24 12:58 UTC, 0atman requested changes
I've made a few small comments here and there, but code all looks really good, obvious improvements in style over what has come before - great :muscle:!

Can I recommend the following tools as essential for any python project:
`black` `flake8` `isort`
And if you're feeling really good, `mypy`!
All pip installable :ok_hand:

2021-02-24 16:13 UTC, kentsanggds commented
Good suggestion with these imports - `black flake8 isort` but as its an open source project and I don't want to impose style of these extensions of which there are a few, and given that I have limited time to do the upgrade work I'll just concentrate on the style issues that have been picked up by reviewers and will slowly improve the code style rather than do a big update as part of this upgrade.

2021-02-24 17:20 UTC, kentsanggds commented on ckanext/spatial/harvesters/base.py
>  from ckanext.harvest.harvesters.base import munge_tag
I'll sort out the files that I touch for now

2021-02-24 17:39 UTC, kentsanggds commented on ckanext/spatial/harvesters/base.py
> +            invalid_tags.append(tag['name'])
I think this is what it is trying to do. 
As this was a commit added from previous DGU approved PR, I'll probably leave this as it is.

2021-02-24 17:39 UTC, kentsanggds commented on ckanext/spatial/tests/test_validation.py
> +        errs = self.get_validation_errors(validation.ISO19139EdenSchema,
ok, will update this for consistency

2021-02-25 11:19 UTC, kentsanggds commented
Closing this PR as superseded by this PR - https://github.com/alphagov/ckanext-spatial/pull/28

2021-02-25 11:19 UTC, closed without merging